-- Expand genAi TMS employee, request, notification and kiosk features.
alter table public.employees
  add column if not exists managed_locations text[] not null default '{}',
  add column if not exists direct_manager_id text null references public.employees(employee_id) on update cascade on delete set null,
  add column if not exists annual_leave_balance numeric(6,2) not null default 12,
  add column if not exists trusted_device_id text null,
  add column if not exists trusted_device_bound_at timestamptz null;
create index if not exists employees_direct_manager_idx on public.employees(direct_manager_id);

create table if not exists public.leave_requests (
  id uuid primary key default gen_random_uuid(),
  employee_id text not null references public.employees(employee_id) on update cascade on delete cascade,
  type text not null check (type in ('Nghỉ phép','Nghỉ ốm','Nghỉ không lương','Công tác','Làm việc tại nhà','WFH')),
  from_date date not null,
  to_date date not null,
  reason text not null default '',
  status text not null default 'Pending' check (status in ('Pending','Approved','Rejected')),
  manager_note text not null default '',
  approver_id text null references public.employees(employee_id) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint leave_requests_date_check check (to_date >= from_date)
);
create index if not exists leave_requests_employee_idx on public.leave_requests(employee_id, created_at desc);
create index if not exists leave_requests_status_idx on public.leave_requests(status, created_at desc);

create table if not exists public.attendance_explanations (
  id uuid primary key default gen_random_uuid(),
  employee_id text not null references public.employees(employee_id) on update cascade on delete cascade,
  attendance_date date not null,
  reason text not null,
  status text not null default 'Pending' check (status in ('Pending','Approved','Rejected')),
  manager_note text not null default '',
  approver_id text null references public.employees(employee_id) on update cascade on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(employee_id, attendance_date)
);
create index if not exists attendance_explanations_employee_idx on public.attendance_explanations(employee_id, created_at desc);
create index if not exists attendance_explanations_status_idx on public.attendance_explanations(status, created_at desc);

create table if not exists public.holidays (
  id bigint generated by default as identity primary key,
  name text not null,
  from_date date not null,
  to_date date not null,
  paid boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint holidays_date_check check (to_date >= from_date)
);
create index if not exists holidays_dates_idx on public.holidays(from_date, to_date);

create table if not exists public.kiosks (
  kiosk_id text primary key,
  name text not null,
  center_id text not null references public.locations(center_id) on update cascade on delete restrict,
  status text not null default 'Active' check (status in ('Active','Inactive')),
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists kiosks_center_idx on public.kiosks(center_id, status);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_employee_id text not null references public.employees(employee_id) on update cascade on delete cascade,
  title text not null,
  body text not null default '',
  type text not null default 'info' check (type in ('info','success','warning','error','request','explanation')),
  action_type text null,
  action_id uuid null,
  read_at timestamptz null,
  created_at timestamptz not null default now()
);
create index if not exists notifications_recipient_idx on public.notifications(recipient_employee_id, created_at desc);
create index if not exists notifications_unread_idx on public.notifications(recipient_employee_id, read_at) where read_at is null;

create or replace function tms_private.current_employee_id()
returns text language sql stable security definer set search_path = '' as $$
  select e.employee_id from public.employees e where e.auth_user_id = auth.uid() and e.status = 'Active' limit 1;
$$;
revoke all on function tms_private.current_employee_id() from public, anon;
grant usage on schema tms_private to authenticated;
grant execute on function tms_private.current_employee_id() to authenticated;

create or replace function tms_private.can_manage_employee(p_employee_id text)
returns boolean language sql stable security definer set search_path = '' as $$
  with actor as (
    select employee_id, role, managed_locations from public.employees where auth_user_id = auth.uid() and status = 'Active' limit 1
  ), target as (
    select employee_id, center_id, direct_manager_id from public.employees where employee_id = p_employee_id
  )
  select exists (
    select 1 from actor a cross join target t
    where a.role in ('Admin','HR')
       or (a.role in ('Director','Manager','Leader') and (t.direct_manager_id = a.employee_id or t.center_id = any(coalesce(a.managed_locations, '{}'::text[]))))
  );
$$;
revoke all on function tms_private.can_manage_employee(text) from public, anon;
grant execute on function tms_private.can_manage_employee(text) to authenticated;

alter table public.leave_requests enable row level security;
alter table public.attendance_explanations enable row level security;
alter table public.holidays enable row level security;
alter table public.kiosks enable row level security;
alter table public.notifications enable row level security;

revoke all on public.leave_requests, public.attendance_explanations, public.holidays, public.kiosks, public.notifications from anon;
grant select, insert, update, delete on public.leave_requests, public.attendance_explanations to authenticated;
grant select, insert, update, delete on public.holidays, public.kiosks to authenticated;
grant select, insert, update on public.notifications to authenticated;
grant usage, select on sequence public.holidays_id_seq to authenticated;

drop policy if exists leave_requests_select on public.leave_requests;
create policy leave_requests_select on public.leave_requests for select to authenticated using (employee_id = (select tms_private.current_employee_id()) or (select tms_private.can_manage_employee(employee_id)));
drop policy if exists leave_requests_insert on public.leave_requests;
create policy leave_requests_insert on public.leave_requests for insert to authenticated with check (employee_id = (select tms_private.current_employee_id()) and status = 'Pending');
drop policy if exists leave_requests_update on public.leave_requests;
create policy leave_requests_update on public.leave_requests for update to authenticated using ((select tms_private.can_manage_employee(employee_id))) with check ((select tms_private.can_manage_employee(employee_id)));
drop policy if exists leave_requests_delete on public.leave_requests;
create policy leave_requests_delete on public.leave_requests for delete to authenticated using (employee_id = (select tms_private.current_employee_id()) and status = 'Pending');

drop policy if exists explanations_select on public.attendance_explanations;
create policy explanations_select on public.attendance_explanations for select to authenticated using (employee_id = (select tms_private.current_employee_id()) or (select tms_private.can_manage_employee(employee_id)));
drop policy if exists explanations_insert on public.attendance_explanations;
create policy explanations_insert on public.attendance_explanations for insert to authenticated with check (employee_id = (select tms_private.current_employee_id()) and status = 'Pending');
drop policy if exists explanations_update on public.attendance_explanations;
create policy explanations_update on public.attendance_explanations for update to authenticated using ((select tms_private.can_manage_employee(employee_id))) with check ((select tms_private.can_manage_employee(employee_id)));
drop policy if exists explanations_delete on public.attendance_explanations;
create policy explanations_delete on public.attendance_explanations for delete to authenticated using (employee_id = (select tms_private.current_employee_id()) and status = 'Pending');

drop policy if exists holidays_read on public.holidays;
create policy holidays_read on public.holidays for select to authenticated using (active or (select tms_private.is_admin()));
drop policy if exists holidays_admin_insert on public.holidays;
create policy holidays_admin_insert on public.holidays for insert to authenticated with check ((select tms_private.is_admin()));
drop policy if exists holidays_admin_update on public.holidays;
create policy holidays_admin_update on public.holidays for update to authenticated using ((select tms_private.is_admin())) with check ((select tms_private.is_admin()));
drop policy if exists holidays_admin_delete on public.holidays;
create policy holidays_admin_delete on public.holidays for delete to authenticated using ((select tms_private.is_admin()));

drop policy if exists kiosks_read on public.kiosks;
create policy kiosks_read on public.kiosks for select to authenticated using ((select tms_private.is_admin()) or (status = 'Active' and exists (select 1 from public.employees e where e.auth_user_id = (select auth.uid()) and e.status = 'Active' and (e.center_id = kiosks.center_id or kiosks.center_id = any(e.allowed_locations)))));
drop policy if exists kiosks_admin_insert on public.kiosks;
create policy kiosks_admin_insert on public.kiosks for insert to authenticated with check ((select tms_private.is_admin()));
drop policy if exists kiosks_admin_update on public.kiosks;
create policy kiosks_admin_update on public.kiosks for update to authenticated using ((select tms_private.is_admin())) with check ((select tms_private.is_admin()));
drop policy if exists kiosks_admin_delete on public.kiosks;
create policy kiosks_admin_delete on public.kiosks for delete to authenticated using ((select tms_private.is_admin()));

drop policy if exists notifications_select on public.notifications;
create policy notifications_select on public.notifications for select to authenticated using (recipient_employee_id = (select tms_private.current_employee_id()) or (select tms_private.is_admin()));
drop policy if exists notifications_update on public.notifications;
create policy notifications_update on public.notifications for update to authenticated using (recipient_employee_id = (select tms_private.current_employee_id()) or (select tms_private.is_admin())) with check (recipient_employee_id = (select tms_private.current_employee_id()) or (select tms_private.is_admin()));
drop policy if exists notifications_insert on public.notifications;
create policy notifications_insert on public.notifications for insert to authenticated with check ((select tms_private.is_admin()));

create or replace function public.get_employee_directory()
returns table (employee_id text, name text, email text, phone text, role text, center_id text, position_title text, department text, avatar_url text, direct_manager_id text)
language sql stable security definer set search_path = '' as $$
  select e.employee_id, e.name, e.email, e.phone, e.role, e.center_id, e.position, e.department, e.avatar_url, e.direct_manager_id
  from public.employees e
  where auth.uid() is not null and exists (select 1 from public.employees me where me.auth_user_id = auth.uid() and me.status = 'Active') and e.status = 'Active'
  order by e.name;
$$;
revoke all on function public.get_employee_directory() from public, anon;
grant execute on function public.get_employee_directory() to authenticated;

create or replace function public.register_or_validate_trusted_device(p_device_id text)
returns table(ok boolean, bound boolean, message text)
language plpgsql security definer set search_path = '' as $$
declare v_employee public.employees%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_device_id is null or length(trim(p_device_id)) < 8 or length(p_device_id) > 160 then return query select false, false, 'Thiết bị không hợp lệ.'; return; end if;
  select * into v_employee from public.employees where auth_user_id = auth.uid() and status = 'Active' for update;
  if not found then return query select false, false, 'Không tìm thấy hồ sơ nhân viên đang hoạt động.'; return; end if;
  if v_employee.trusted_device_id is null or v_employee.trusted_device_id = '' then
    update public.employees set trusted_device_id = p_device_id, trusted_device_bound_at = now(), updated_at = now() where employee_id = v_employee.employee_id;
    return query select true, true, 'Đã đăng ký thiết bị tin cậy.';
  elsif v_employee.trusted_device_id = p_device_id then return query select true, false, 'Thiết bị đã được xác thực.';
  else return query select false, false, 'Tài khoản đã liên kết với thiết bị khác. Liên hệ quản trị viên để đặt lại thiết bị.';
  end if;
end; $$;
revoke all on function public.register_or_validate_trusted_device(text) from public, anon;
grant execute on function public.register_or_validate_trusted_device(text) to authenticated;

create or replace function public.review_leave_request(p_id uuid, p_status text, p_note text default '')
returns void language plpgsql security definer set search_path = '' as $$
declare v_request public.leave_requests%rowtype; v_actor text;
begin
  if p_status not in ('Approved','Rejected') then raise exception 'Invalid status'; end if;
  select * into v_request from public.leave_requests where id = p_id for update;
  if not found then raise exception 'Request not found'; end if;
  if not tms_private.can_manage_employee(v_request.employee_id) then raise exception 'Forbidden'; end if;
  select tms_private.current_employee_id() into v_actor;
  update public.leave_requests set status = p_status, manager_note = coalesce(p_note,''), approver_id = v_actor, updated_at = now() where id = p_id;
end; $$;
revoke all on function public.review_leave_request(uuid,text,text) from public, anon;
grant execute on function public.review_leave_request(uuid,text,text) to authenticated;

create or replace function public.review_attendance_explanation(p_id uuid, p_status text, p_note text default '')
returns void language plpgsql security definer set search_path = '' as $$
declare v_item public.attendance_explanations%rowtype; v_actor text;
begin
  if p_status not in ('Approved','Rejected') then raise exception 'Invalid status'; end if;
  select * into v_item from public.attendance_explanations where id = p_id for update;
  if not found then raise exception 'Explanation not found'; end if;
  if not tms_private.can_manage_employee(v_item.employee_id) then raise exception 'Forbidden'; end if;
  select tms_private.current_employee_id() into v_actor;
  update public.attendance_explanations set status = p_status, manager_note = coalesce(p_note,''), approver_id = v_actor, updated_at = now() where id = p_id;
end; $$;
revoke all on function public.review_attendance_explanation(uuid,text,text) from public, anon;
grant execute on function public.review_attendance_explanation(uuid,text,text) to authenticated;

create or replace function public.mark_notification_read(p_id uuid)
returns void language sql security invoker set search_path = '' as $$ update public.notifications set read_at = coalesce(read_at, now()) where id = p_id; $$;
revoke all on function public.mark_notification_read(uuid) from public, anon;
grant execute on function public.mark_notification_read(uuid) to authenticated;

create or replace function public.notify_tms_review_result()
returns trigger language plpgsql security definer set search_path = '' as $$
declare v_title text; v_type text;
begin
  if old.status = new.status or new.status = 'Pending' then return new; end if;
  v_type := case when tg_table_name = 'leave_requests' then 'request' else 'explanation' end;
  v_title := case when tg_table_name = 'leave_requests' then 'Yêu cầu đã được xử lý' else 'Giải trình đã được xử lý' end;
  insert into public.notifications(recipient_employee_id,title,body,type,action_type,action_id)
  values (new.employee_id, v_title, case when new.status = 'Approved' then 'Đã duyệt' else 'Đã từ chối' end || case when coalesce(new.manager_note,'') <> '' then ': ' || new.manager_note else '' end, v_type, v_type, new.id);
  return new;
end; $$;
revoke all on function public.notify_tms_review_result() from public, anon, authenticated;
drop trigger if exists leave_requests_notify_status on public.leave_requests;
create trigger leave_requests_notify_status after update of status on public.leave_requests for each row execute function public.notify_tms_review_result();
drop trigger if exists explanations_notify_status on public.attendance_explanations;
create trigger explanations_notify_status after update of status on public.attendance_explanations for each row execute function public.notify_tms_review_result();
